version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pip (bot)
  - package-ecosystem: "pip"
    directory: "/bot"
    schedule:
      interval: "weekly"
