version: '3.8'

services:
  web:
    # Имя образа будет подставлено из переменных GitLab CI
    image: ${CI_REGISTRY_IMAGE}/web:${WEB_IMAGE_TAG}
    ports:
      - "5000:5000"
    env_file: ./.env
    depends_on:
      - db
      - api

  api:
    image: ${CI_REGISTRY_IMAGE}/api:${API_IMAGE_TAG}
    ports:
      - "8000:8000"
    env_file: ./.env

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env

volumes:
  postgres_data: