name: Deploy to Server

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "Starting deployment..."
          
          # Обновляем docker-compose файлы
          cd /opt/mutil || mkdir -p /opt/mutil && cd /opt/mutil
          
          # Скачиваем последние docker-compose файлы из репозитория
          curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/docker/docker-compose.yml
          
          # Останавливаем текущие контейнеры
          docker-compose down
          
          # Подтягиваем последние образы
          docker-compose pull
          
          # Запускаем новые контейнеры
          docker-compose up -d
          
          # Удаляем неиспользуемые образы
          docker image prune -f
          
          echo "Deployment completed successfully!"
